defmodule YellowDog.Dns.AclStore do
  @moduledoc """
  Persistence layer for custom named ACL configurations.

  Handles loading and saving named ACL definitions from/to TOML files.
  Named ACLs can be referenced by views for access control.

  ## File Format

  ACLs are stored in TOML format:

      [[acl]]
      name = "internal"
      description = "Internal network clients"

      [[acl.rules]]
      action = "allow"
      network = "10.0.0.0/8"

      [[acl.rules]]
      action = "allow"
      network = "192.168.0.0/16"

      [[acl]]
      name = "north_america"
      description = "North American clients"

      [[acl.rules]]
      action = "allow"
      geo_countries = ["US", "CA", "MX"]
  """

  require Logger

  @type acl_rule :: %{
          action: String.t(),
          network: String.t() | nil,
          geo_countries: [String.t()] | nil
        }

  import YellowDog.Config.TomlHelpers,
    only: [parse_toml: 1, get_value: 2, get_value: 3, get_list: 3, encode_toml_string: 1, ensure_directory: 1, atomic_write: 2]

  @type acl_config :: %{
          name: String.t(),
          description: String.t() | nil,
          rules: [acl_rule()]
        }

  @doc """
  Loads named ACLs from a TOML file.

  ## Parameters
  - `file_path` - Path to the ACLs TOML file

  ## Returns
  - `{:ok, [acl_config]}` on success
  - `{:error, reason}` on failure (returns empty list for missing file)
  """
  @spec load_acls(String.t()) :: {:ok, [acl_config()]} | {:error, term()}
  def load_acls(file_path) do
    with {:ok, content} <- File.read(file_path),
         {:ok, raw_data} <- parse_toml(content),
         {:ok, acls} <- extract_acls(raw_data) do
      validated_acls =
        for acl <- acls,
            {:ok, validated} <- [validate_and_normalize_acl(acl)],
            do: validated

      {:ok, validated_acls}
    else
      {:error, :enoent} ->
        {:ok, []}

      {:error, reason} = error ->
        Logger.warning("Failed to load ACLs", file_path: file_path, error: inspect(reason))
        error
    end
  end

  @doc """
  Saves named ACLs to a TOML file.

  ## Parameters
  - `file_path` - Path to save the ACLs file
  - `acls` - List of ACL configurations
  """
  @spec save_acls(String.t(), [acl_config()]) :: :ok | {:error, term()}
  def save_acls(file_path, acls) do
    with {:ok, content} <- format_acls(acls),
         :ok <- ensure_directory(file_path),
         :ok <- atomic_write(file_path, content) do
      :ok
    end
  end

  # Private functions

  defp extract_acls(data) do
    case Map.get(data, "acl") do
      nil -> {:ok, []}
      acls when is_list(acls) -> {:ok, acls}
      acl when is_map(acl) -> {:ok, [acl]}
    end
  end

  defp validate_and_normalize_acl(acl) do
    normalized = normalize_acl_keys(acl)

    if is_nil(normalized.name) or normalized.name == "" do
      {:error, "ACL name is required"}
    else
      {:ok, normalized}
    end
  end

  defp normalize_acl_keys(acl) when is_map(acl) do
    %{
      name: get_value(acl, [:name, "name"]),
      description: get_value(acl, [:description, "description"]),
      rules: normalize_rules(acl)
    }
  end

  defp normalize_rules(acl) do
    case get_value(acl, [:rules, "rules"]) do
      nil -> []
      rules when is_list(rules) -> Enum.map(rules, &normalize_rule/1)
      rule when is_map(rule) -> [normalize_rule(rule)]
    end
  end

  defp normalize_rule(rule) when is_map(rule) do
    base = %{
      action: get_value(rule, [:action, "action"], "allow")
    }

    geo_countries = get_list(rule, [:geo_countries, "geo_countries"], [])
    network = get_value(rule, [:network, "network"])

    cond do
      geo_countries != [] ->
        Map.put(base, :geo_countries, geo_countries)

      network != nil ->
        Map.put(base, :network, network)

      true ->
        base
    end
  end

  defp format_acls(acls) do
    header = """
    # DNS Named ACL Configuration
    # Generated by YellowDog DNS
    #
    # Named ACLs can be referenced by views for access control.
    # Each ACL has a name, optional description, and a list of rules.
    """

    acls_content = Enum.map_join(acls, "\n", &acl_to_toml/1)

    {:ok, header <> "\n" <> acls_content}
  end

  defp acl_to_toml(acl) do
    lines = [
      "",
      "[[acl]]",
      "name = #{encode_toml_string(acl.name)}"
    ]

    lines =
      if acl[:description] && acl.description != "" do
        lines ++ ["description = #{encode_toml_string(acl.description)}"]
      else
        lines
      end

    # Add rules
    rules_lines =
      Enum.flat_map(acl.rules || [], fn rule ->
        rule_lines = [
          "",
          "[[acl.rules]]",
          "action = #{encode_toml_string(to_string(rule.action))}"
        ]

        cond do
          Map.has_key?(rule, :geo_countries) and is_list(rule.geo_countries) ->
            countries_str = Enum.map_join(rule.geo_countries, ", ", &encode_toml_string/1)
            rule_lines ++ ["geo_countries = [#{countries_str}]"]

          Map.has_key?(rule, :network) and rule.network != nil ->
            rule_lines ++ ["network = #{encode_toml_string(rule.network)}"]

          true ->
            rule_lines
        end
      end)

    Enum.join(lines ++ rules_lines, "\n")
  end

end
