import Config

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :yellow_dog_console, YellowDog.Console.Endpoint,
  # Binding to all interfaces to allow access from other machines.
  # Use `ip: {127, 0, 0, 1}` to bind only to localhost.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "xsqEOmOqmfV082AmjacS5DWwWUPmGhzmBaRFKrW0swiqprhSDd0qU39W6GkVZBCX",
  watchers: [
    bun: {Bun, :install_and_run, [:yellow_dog_console, ~w(--watch)]},
    tailwind: {Tailwind, :install_and_run, [:yellow_dog_console, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :yellow_dog_console, YellowDog.Console.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/yellow_dog/console/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :yellow_dog_console, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :logger, :console, level: :debug

# YellowDog Telemetry Configuration for Development
config :yellow_dog_telemetry,
  level: :debug,
  format: :pretty,
  console_colors: true,
  show_spans: true,
  show_span_start: false,
  span_threshold_ms: 0,
  filter_apps: nil,
  exclude_apps: nil,
  app_levels: %{},
  span_thresholds: %{}
