import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :yellow_dog_console, YellowDog.Console.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :yellow_dog_console, YellowDog.Console.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :logger, :console, level: :warning

# YellowDog Telemetry Configuration for Production
config :yellow_dog_telemetry,
  level: :info,
  format: :json,
  console_colors: false,
  show_spans: true,
  show_span_start: false,
  span_threshold_ms: 100,
  filter_apps: nil,
  exclude_apps: nil,
  app_levels: %{
    # Less verbose for web console in production
    yellow_dog_console: :warn
  },
  span_thresholds: %{}
