defmodule YellowDog.Console.Endpoint do
  @moduledoc """
  Phoenix endpoint for the YellowDog web console.

  Handles HTTP/WebSocket connections and configures:
  - Static file serving from priv/static
  - LiveView socket connections
  - Session management via signed cookies
  - Request logging and parsing

  Configure via `:yellow_dog_console` application environment.
  """

  use Phoenix.Endpoint, otp_app: :yellow_dog_console

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_yellow_dog_console_key",
    signing_salt: "KP2GKi8w",
    same_site: "Lax",
    http_only: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/netman/ws", YellowDog.Console.NetmanSocket, websocket: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :yellow_dog_console,
    gzip: not code_reloading?,
    only: YellowDog.Console.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader, reloader: &YellowDog.Console.CodeReloader.reload/2
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug YellowDog.Console.Router
end
